<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>pl.przyklady</groupId>
    <artifactId>5ppMaven</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.release>25</maven.compiler.release>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <junit.version>5.14.2</junit.version>
        <surefire.version>3.5.2</surefire.version>
        <surefire.report.version>3.5.2</surefire.report.version>
        <jacoco.version>0.8.14</jacoco.version>
    </properties>

    <dependencies>

        <!-- JUnit 5 -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <!-- Kompilator Java -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>

                <configuration>
                    <release>25</release>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>


            <!-- JaCoCo -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>

                <executions>

                    <!--
                        Dodaje agenta JaCoCo do JVM
                        przed uruchomieniem testów
                    -->
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>

                    <!--
                        Generowanie raportu JaCoCo
                        podczas fazy verify
                    -->
                    <execution>
                        <id>jacoco-report</id>
                        <phase>verify</phase>

                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>

                </executions>
            </plugin>


            <!-- Maven Surefire -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire.version}</version>

                <configuration>

                    <!--
                        @{argLine} zachowuje parametry
                        przekazane przez JaCoCo
                    -->
                    <argLine>
                        @{argLine} -Dfile.encoding=UTF-8
                    </argLine>

                    <!-- pokazuje pełne informacje o testach -->
                    <printSummary>true</printSummary>

                    <!-- nie przekierowuje konsoli do pliku -->
                    <redirectTestOutputToFile>false</redirectTestOutputToFile>

                </configuration>
            </plugin>


            <!-- Surefire Report -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-report-plugin</artifactId>
                <version>${surefire.report.version}</version>
            </plugin>


            <!-- Maven Site -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.21.0</version>
            </plugin>

        </plugins>
    </build>


    <!-- Raporty Maven Site -->
    <reporting>

        <plugins>

            <!-- Raport Surefire -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-report-plugin</artifactId>
                <version>${surefire.report.version}</version>
            </plugin>


            <!-- Raport JaCoCo -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>

                <reportSets>

                    <reportSet>

                        <reports>
                            <report>report</report>
                        </reports>

                    </reportSet>

                </reportSets>

            </plugin>

        </plugins>

    </reporting>

</project>